---
abstract: 'use Merriam-Webster dictionary API in Perl '
author:
  - 'Hao Wu <echowuhao@gmail.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-MerriamWebster
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Moose: '0'
  URI::Escape: '0'
  XML::LibXML: '0'
  perl: v5.14.0
resources:
  bugtracker: https://github.com/swuecho/Net-MW-API/issues
  homepage: https://github.com/swuecho/Net-MW-API
  repository: https://github.com/swuecho/Net-MW-API.git
version: '0.10'
x_contributors:
  - 'Hao <echowuhao@gmail.com>'
  - 'Hao Wu <hwu@intellisurvey.com>'
